Voornaam = input("Voornaam:")
Achternaam = input("Achternaam:")
Straatnaam = input("Straatnaam:")
Huisnummer = input("Huisnummer:")
Postcode = input("Postcode:")
Woonplaats = input("Woonplaats:")

print("Uw gegevens:")
print("-------------------------------------------")
print("|  Voornaam  : ", Voornaam,"")
print("|  Achternaam: ", Achternaam,"")
print("|  Straatnaam: ", Straatnaam,"")
print("|  Huisnummer: ", Huisnummer,"")
print("|  Postcode  : ", Postcode,"")
print("|  Woonplaats: ", Woonplaats,"")
print("-------------------------------------------")